version: 2.1

orbs:
  python: circleci/python@2.1.1
  python-lib: dialogue/python-lib@0.1.55

jobs:
  # Check if the PR is a draft
  check-if-pr-is-draft:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install jq and curl
          command: sudo apt-get update && sudo apt-get install -y jq curl
      - run:
          name: Check if PR is a draft
          command: ./check_pr_status.sh

  # Compatibility check across all supported versions
  check_compatibility:
    parameters:
      python_version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y jq curl
            python -m pip install --upgrade pip
            pip install requests packaging
      - run:
          name: Check compatibility for Python << parameters.python_version >>
          command: |
            python .circleci/check_compatibility.py << parameters.python_version >>

  # Linting with Ruff (Run once on the latest Python version)
  ruff:
    resource_class: small
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - restore_cache:
          name: Restore cached Ruff venv
          keys:
            - v2-pypi-py-ruff-3.12.0
      - run:
          name: Update & Activate Ruff venv
          command: |
            python -m venv .venv
            . .venv/bin/activate
            python -m pip install --upgrade pip
            pip install ruff
      - save_cache:
          name: Save cached Ruff venv
          paths:
            - ".venv/"
          key: v2-pypi-py-ruff-3.12.0
      - run:
          name: Ruff linting
          command: |
            . .venv/bin/activate
            ruff check .

workflows:
  version: 2
  main_workflow:
    jobs:
      - check-if-pr-is-draft

      # Compatibility checks for multiple Python versions
      - check_compatibility:
          requires:
            - check-if-pr-is-draft
          python_version: "3.9.0"
          name: check-compatibility-3.9.0
      - check_compatibility:
          requires:
            - check-if-pr-is-draft
          python_version: "3.10.0"
          name: check-compatibility-3.10.0
      - check_compatibility:
          requires:
            - check-if-pr-is-draft
          python_version: "3.11.0"
          name: check-compatibility-3.11.0
      - check_compatibility:
          requires:
            - check-if-pr-is-draft
          python_version: "3.12.0"
          name: check-compatibility-3.12.0

      # Linting workflow using Ruff
      - ruff:
          requires:
            - check-if-pr-is-draft
